### ISSUE TITLE
[BUG - next-pwa]: Dependency breaks depcheck

### ISSUE THREAD

**Issue by aaronabf** [DuCanhGH/next-pwa#27]
### Provide environment information

```
"next": "13.4.1",
"@ducanh2912/next-pwa": "8.5.1",
"depcheck": "1.4.3",
```

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

n/a

### To reproduce

`depcheck ...`

### Describe the bug

As mentioned [here](https://github.com/depcheck/depcheck/issues/545), this dependency breaks depcheck:
```
Next.js webpack configuration detection failed with the following error TypeError: Cannot read properties of undefined (reading 'distDir')
    at Object.webpack (/repo/node_modules/@ducanh2912/next-pwa/dist/index.cjs:1:15322)
    at Object.webpack (/repo/node_modules/@next/bundle-analyzer/index.js:22:29)
    at loadNextWebpackConfig (/repo/node_modules/depcheck/dist/special/webpack.js:157:25)
    at parseWebpack (/repo/node_modules/depcheck/dist/special/webpack.js:187:27)
    at getDependencies (/repo/node_modules/depcheck/dist/check.js:71:24)
    at /repo/node_modules/depcheck/dist/check.js:97:32
    at Array.map (<anonymous>)
    at checkFile (/repo/node_modules/depcheck/dist/check.js:97:18)
    at ReaddirpStream.<anonymous> (/repo/node_modules/depcheck/dist/check.js:126:24)
    at ReaddirpStream.emit (node:events:511:28) Support for this feature is new and experimental, please report issues at https://github.com/depcheck/depcheck/issues
```

### Expected behavior

Depcheck should run to completion with no errors.

**Comment by aaronabf** [comment]
I see. If it's their mocking seems silly to update this library to handle. I can open a ticket with them.
