### ISSUE TITLE
Pop up Instal PWA

### ISSUE THREAD

**Issue by dimasandriano** [DuCanhGH/next-pwa#86]
### Provide environment information

-

### Whose documentation is this feedback for?

@ducanh2912/next-pwa

### Describe the problem

How to implement pop up for instal pwa? Is there an example?

### Expected behavior

-

**Comment by DuCanhGH** [comment]
https://github.com/DuCanhGH/next-pwa/blob/master/examples/lifecycle/components/PWALifecycle.tsx

**Comment by DuCanhGH** [comment]
@dimasandriano have you successfully implemented the popup? If yes, please close the issue :) Otherwise, please describe what issue you are getting.

**Comment by tine-krueger** [comment]
@DuCanhGH , I tried to implement this popup, but the wb.messageSkipWaiting() did not activate the new worker. 
I have the following error in the console: 
`sw.js:1 Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:3000/workbox-8e51679a.js' failed to load.
    at http://localhost:3000/sw.js:1:214
    at new Promise (<anonymous>)
    at n (http://localhost:3000/sw.js:1:77)
    at c (http://localhost:3000/sw.js:1:468)
    at http://localhost:3000/sw.js:1:547
    at Array.map (<anonymous>)
    at http://localhost:3000/sw.js:1:533
    at http://localhost:3000/sw.js:1:579`

**Comment by tine-krueger** [comment]
@DuCanhGH , I tried to implement this popup but the messageSkipWaiting() method did not activate the service worker. I have the following error in the console:

```
sw.js:1 Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:3000/workbox-8e51679a.js' failed to load.
    at http://localhost:3000/sw.js:1:214
    at new Promise (<anonymous>)
    at n (http://localhost:3000/sw.js:1:77)
    at c (http://localhost:3000/sw.js:1:468)
    at http://localhost:3000/sw.js:1:547
    at Array.map (<anonymous>)
    at http://localhost:3000/sw.js:1:533
    at http://localhost:3000/sw.js:1:579
```

**Comment by tine-krueger** [comment]
@DuCanhGH , I have to correct: It works like charm. I just had to listen to the message to skip in my custom worker. 
```
self.addEventListener('message', (event) => {
	if (event.data && event.data.type === 'SKIP_WAITING') {
		self.skipWaiting()
	}
})
```
